### ISSUE TITLE
jqM beta 1 - rebind clicks

### ISSUE THREAD

**Issue by zephster** [hiroprotagonist/jquery.mobile.actionsheet#5]
You need to re-bind your click events to vclick for it to work in beta 1. Just a heads up.

**Comment by hiroprotagonist** [comment]
Right. Virtual Event corruption layer had too much bugs in alpha4. Will switch to Virtual Events soon.

**Comment by abernardobr** [comment]
Just tried to use for jqm beta2 and it is not working. It shows the wallpaper but it does not show the contents. I ran the example index.html used here.

**Comment by zephster** [comment]
I'll update my fork tomorrow, mine works just fine.

**Comment by abernardobr** [comment]
Ok great! Thanks for your response.

Regards,

Augusto

On 8/10/11 7:59 PM, "zephster"
reply@reply.github.com
 wrote:

**Comment by zephster** [comment]
Check this commit:
https://github.com/zephster/jquery.mobile.actionsheet/commit/eedba7d0eef8d37e511d48cc661bf83b532e5d05
Hopefully that'll work for you. Works for me on jqmobile beta 2.

**Comment by abernardobr** [comment]
Hello there,

I tried using the commit you've done but still can't make it work. I am
not sure I have my HTML tags corretly.

If you can send me a small sample HTML, js and css that works, it would
help me a lot.

Thanks for the responses and for making this available to use.

Best regards,

Augusto

On 8/11/11 10:08 AM, "zephster"
reply@reply.github.com
 wrote:

**Comment by zephster** [comment]
It would be difficult for me to post my javascript because there's a lot of customizations I made, but I'll try to make this a good example.

``` css
/* dimmed background */
.ui-actionsheet-wallpaper { 
    display: none;
    background-color: black; 
    opacity: .3;
    position: absolute;
    top:0;
    left: 0;
    min-height: 100%; 
    height: auto;
    width: 100%;
}
/* sheet popup window */
.ui-actionsheet-content {
    -moz-border-radius: 8px;
    -webkit-border-radius: 8px;
    border-radius: 8px;
    background-color: silver;
    border-style: solid;
    border-width: 3px;
    display: none;
    height: auto;
    position: absolute;
    width: 230px;
    z-index: 20;
    -moz-box-shadow: 0px 0px 12px rgba(0,0,0,.6);
    -webkit-box-shadow: 0px 0px 12px rgba(0,0,0,.6);
    box-shadow: 0px 0px 12px rgba(0,0,0,.6); 
}
```

Left out the animation keyframes, for brevity.

The .js file is the one in my last commit.

Here's my HTML code...there's some PHP mixed in there, sorry about that, but you can probably figure out what goes where. In this case, I'm using it as an 'edit item' field in a shopping cart I built for mobile devices.

``` html
<a class="sheet" data-role="actionsheet" data-sheet="EXAMPLESHEET">click here to view the actionsheet</a>

<div class="cart_sheet" sheet="EXAMPLESHEET">
    <div class="sheet_name">' . $item['name'] . '</div>
    <div class="qty_desc">Drag the slider to the desired quantity.</div>
    <div class="qty_slider">
        <input type="range" class="qty_edited" id="' . $item['rowid'] . '" value="' . $item['qty'] . '" min="1" max="20">
    </div>
    <input type="button" class="qty_save" data-theme="b" data-rel="close" value="Save Quantity">
    <input type="button" class="item_remove" data-theme="e" data-rel="close" value="Remove Item">
    <hr>
    <input type="button" data-theme="a" data-rel="close" value="Cancel">
</div>
```
